const { test } = require('node:test')
const assert = require('node:assert/strict')
const { mkdtempSync, readFileSync, rmSync } = require('node:fs')
const { tmpdir } = require('node:os')
const path = require('node:path')
const { criarServidor } = require('./server.cjs')

test('contrato HTTP, filtros, relações, CRUD e persistência', async (t) => {
  process.env.NODE_ENV = 'test'
  const pasta = mkdtempSync(path.join(tmpdir(), 'balaio-api-'))
  const arquivo = path.join(pasta, 'db.json')
  const servidor = criarServidor(arquivo).listen(0, '127.0.0.1')
  await new Promise((resolve) => servidor.once('listening', resolve))
  t.after(async () => {
    await new Promise((resolve) => servidor.close(resolve))
    rmSync(pasta, { recursive: true, force: true })
  })
  const base = `http://127.0.0.1:${servidor.address().port}/api/v1`
  const request = async (url, body, method = 'POST', headers = {}) => {
    const opcoes = body === undefined && Object.keys(headers).length === 0
      ? undefined
      : { method: body === undefined ? method : method, headers: { 'Content-Type': 'application/json', ...headers }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) }
    const res = await fetch(base + url, opcoes)
    return { status: res.status, cookie: res.headers.get('set-cookie'), ...await res.json() }
  }
  for (const recurso of ['pecas', 'artesaos', 'coletivos', 'eventos', 'videos', 'pedidos', 'artesao/conversas', 'artesao/pedidos-pendentes', 'admin/curadoria', 'admin/mediacoes']) {
    const res = await request('/' + recurso)
    assert.equal(res.status, 200, recurso)
    assert.equal(res.erro, null, recurso)
    assert.ok(res.dados.length > 0, recurso)
  }
  assert.ok((await request('/referencias')).dados.tecnicas.length)
  assert.equal((await request('/usuario')).status, 401)
  assert.equal((await request('/auth/cadastro', { nome: '', email: 'invalido', senha: '123' })).status, 400)
  const cadastro = await request('/auth/cadastro', { nome: 'Ally Show', email: 'ALLYSHOW@gmail.com', senha: 'senhaforte', perfil: 'comprador' })
  assert.equal(cadastro.status, 201)
  assert.equal(cadastro.dados.email, 'allyshow@gmail.com')
  assert.ok(!('senhaHash' in cadastro.dados))
  const cookie = cadastro.cookie.split(';')[0]
  assert.equal((await request('/usuario', undefined, 'GET', { Cookie: cookie })).dados.nome, 'Ally Show')
  const endereco = await request('/usuario/enderecos', { apelido: 'Casa', rua: 'Rua do teste, 1', bairro: 'Centro', cep: '50000-000' }, 'POST', { Cookie: cookie })
  assert.equal(endereco.status, 201)
  assert.equal((await request(`/usuario/enderecos/${endereco.dados.id}`, { rua: 'Rua atualizada, 2' }, 'PATCH', { Cookie: cookie })).dados.rua, 'Rua atualizada, 2')
  assert.equal((await request('/usuario', { nome: 'Ally Atualizado', email: 'allyshow@gmail.com', telefone: '81999990000' }, 'PATCH', { Cookie: cookie })).dados.nome, 'Ally Atualizado')
  assert.equal((await request('/auth/cadastro', { nome: 'Outro', email: 'allyshow@gmail.com', senha: 'senhaforte' })).status, 409)
  assert.equal((await request('/auth/logout', {}, 'POST', { Cookie: cookie })).status, 200)
  assert.equal((await request('/usuario', undefined, 'GET', { Cookie: cookie })).status, 401)
  assert.equal((await request('/auth/login', { email: 'allyshow@gmail.com', senha: 'errada' })).status, 401)
  const login = await request('/auth/login', { email: 'allyshow@gmail.com', senha: 'senhaforte' })
  assert.equal(login.status, 200)
  assert.ok(login.cookie)
  assert.equal((await request('/auth/recuperacao', { email: 'allyshow@gmail.com' })).status, 201)
  const vendedor = await request('/auth/cadastro', { nome: 'Artesã Teste', email: 'artesa@teste.com', senha: 'senhaforte', perfil: 'artesao', territorio: 'Cariri', tecnica: 'Xilogravura' })
  assert.equal(vendedor.status, 201)
  assert.ok(vendedor.dados.artesaoId)
  const cookieVendedor = vendedor.cookie.split(';')[0]
  assert.equal((await request('/artesao/me', undefined, 'GET', { Cookie: cookieVendedor })).dados.nome, 'Artesã Teste')
  assert.equal((await request('/artesao/me', { atelie: 'Novo Ateliê' }, 'PATCH', { Cookie: cookieVendedor })).dados.atelie, 'Novo Ateliê')
  const estado = await request('/estado')
  const cookieCliente = estado.cookie.split(';')[0]
  assert.deepEqual((await request('/estado/favoritos', { favoritos: ['teste'] }, 'PUT', { Cookie: cookieCliente })).dados, ['teste'])
  assert.deepEqual((await request('/estado/videosCurtidos', { videosCurtidos: ['v-001'] }, 'PUT', { Cookie: cookieCliente })).dados, ['v-001'])
  assert.deepEqual((await request('/estado', undefined, 'GET', { Cookie: cookieCliente })).dados.videosCurtidos, ['v-001'])
  const todas = await request('/pecas')
  const pagina = await request('/pecas?pagina=2&tamanho=3&ordenar=preco-asc')
  assert.equal(pagina.dados.length, 3)
  assert.equal(pagina.paginacao.total, todas.dados.length)
  assert.equal(pagina.paginacao.pagina, 2)
  const preco = (p) => p.preco * (1 - (p.desconto || 0) / 100)
  assert.deepEqual(pagina.dados.map(preco), [...pagina.dados.map(preco)].sort((a, b) => a - b))
  assert.ok((await request('/pecas?q=ceramica')).dados.length)
  assert.equal((await request('/pecas?q=inexistente')).paginacao.total, 0)
  const primeira = todas.dados[0]
  const pergunta = await request(`/pecas/${primeira.slug}/perguntas`, { pergunta: 'Como foi feita?' }, 'POST', { Cookie: login.cookie.split(';')[0] })
  assert.equal(pergunta.status, 201)
  assert.equal((await request(`/pecas/${primeira.slug}/perguntas`)).dados[0].pergunta, 'Como foi feita?')
  const relacionadas = await request(`/pecas/${primeira.slug}/relacionadas?limite=1`)
  assert.equal(relacionadas.dados.length, 1)
  assert.notEqual(relacionadas.dados[0].slug, primeira.slug)
  assert.ok((await request(`/artesaos/${primeira.artesao}/pecas`)).dados.every((p) => p.artesao === primeira.artesao))
  assert.equal((await request('/pecas/inexistente')).status, 404)
  assert.equal((await request('/pedidos/inexistente/conversa')).status, 404)
  const evento = (await request('/eventos')).dados[0]
  const novo = await request('/eventos', { ...evento, id: undefined, slug: 'evento-teste', nome: 'Evento de teste' })
  assert.equal(novo.status, 201)
  assert.equal((await request('/eventos/evento-teste')).dados.nome, 'Evento de teste')
  assert.equal((await request('/eventos', { ...evento, slug: 'evento-teste' })).status, 409)
  assert.equal((await request('/eventos/evento-teste', { nome: 'Atualizado' }, 'PATCH')).dados.nome, 'Atualizado')
  const compra = { itens: [{ slug: primeira.slug, quantidade: 1 }, { slug: todas.dados[1].slug, quantidade: 2 }], freteId: 'padrao', meio: 'pix', endereco: { cep: '52021030', endereco: 'Rua de teste', cidade: 'Recife', estado: 'PE' } }
  const cookieComprador = login.cookie.split(';')[0]
  const pedido = await request('/checkout', compra, 'POST', { Cookie: cookieComprador })
  assert.equal(pedido.status, 201)
  assert.equal(pedido.dados.total, Math.round((preco(primeira) + 2 * preco(todas.dados[1]) + 38.9) * 100) / 100)
  assert.equal(pedido.dados.itens.length, 2)
  assert.ok((await request('/pedidos', undefined, 'GET', { Cookie: cookieComprador })).dados.some((item) => item.id === pedido.dados.id))
  assert.ok(!(await request('/pedidos', undefined, 'GET', { Cookie: cookieVendedor })).dados.some((item) => item.id === pedido.dados.id))
  const emProducao = await request(`/pedidos/${pedido.dados.id}/estado`, { estado: 'producao' }, 'PATCH')
  assert.equal(emProducao.dados.estado, 'producao')
  assert.equal(emProducao.dados.etapas.find((etapa) => etapa.estado === 'producao').atual, true)
  assert.equal((await request('/checkout', { ...compra, itens: [] })).status, 400)
  const mensagem = await request(`/pedidos/${pedido.dados.id}/conversa`, { texto: 'Olá!', autor: 'comprador', hora: 'agora' })
  assert.equal(mensagem.status, 201)
  assert.equal((await request(`/pedidos/${pedido.dados.id}/conversa`)).dados.length, 1)
  assert.equal((await request('/pedidos/PE-2026-8720/conversa')).dados.length, 0)
  const disco = JSON.parse(readFileSync(arquivo, 'utf8'))
  for (const [nome, colecao] of Object.entries(disco)) {
    if (Array.isArray(colecao)) assert.ok(colecao.every((item) => item.id !== undefined), `${nome} contém item sem id`)
  }
  assert.ok(disco.usuarios.some((usuario) => usuario.email === 'allyshow@gmail.com' && usuario.senhaHash))
  assert.ok(!disco.usuarios.some((usuario) => 'senha' in usuario))
  assert.ok(disco.pedidos.some((p) => p.id === pedido.dados.id))
  assert.equal(disco.eventos.find((e) => e.slug === 'evento-teste').nome, 'Atualizado')
  assert.equal((await request('/eventos/evento-teste', {}, 'DELETE')).status, 200)
  assert.equal((await request('/eventos/evento-teste')).status, 404)
  const pecaNova = { ...primeira, id: undefined, slug: 'peca-teste', situacao: 'curadoria' }
  assert.equal((await request('/pecas', pecaNova)).status, 201)
  assert.ok(!(await request('/pecas')).dados.some((p) => p.slug === 'peca-teste'))
  const fila = (await request('/admin/curadoria')).dados.find((p) => p.pecaSlug === 'peca-teste')
  assert.ok(fila)
  assert.equal((await request(`/admin/curadoria/${fila.id}/decisao`, { decisao: 'aprovada' })).status, 200)
  assert.ok((await request('/pecas')).dados.some((p) => p.slug === 'peca-teste'))
  assert.equal((await request('/pecas/peca-teste', { preco: 321 }, 'PATCH')).dados.preco, 321)
  assert.equal((await request('/pecas/peca-teste', {}, 'DELETE')).status, 200)
  assert.equal((await request('/pecas/peca-teste')).status, 404)
  assert.equal((await request('/pedidos/PE-2026-8720/avaliacao', { nota: 0 })).status, 400)
  assert.equal((await request('/pedidos/PE-2026-8720/avaliacao', { nota: 5, comentario: 'Ótima peça', aspectos: [] })).status, 201)
  assert.equal((await request('/pedidos/PE-2026-8720')).dados.avaliado, true)
  assert.equal((await request('/pedidos/PE-2026-8720/avaliacao', { nota: 5 })).status, 409)
  const mediacao = { id: 'MED-teste', pedido: pedido.dados.id, assunto: 'Ajuda', relato: 'Preciso de ajuda', solucao: 'conversa' }
  assert.equal((await request('/admin/mediacoes', mediacao)).status, 201)
  assert.equal((await request('/admin/mediacoes', mediacao)).status, 409)
  assert.equal((await request('/eventos?lat=-8&lng=-35')).dados.length, (await request('/eventos')).dados.length)
  assert.equal((await request('/eventos?lat=200&lng=0')).status, 400)
})
