const { test } = require('node:test')
const assert = require('node:assert/strict')
const { mkdtempSync, readFileSync, rmSync, writeFileSync } = require('node:fs')
const { tmpdir } = require('node:os')
const path = require('node:path')
const { criarServidor } = require('./server.cjs')

test('contrato HTTP, filtros, relações, CRUD e persistência', async (t) => {
  process.env.NODE_ENV = 'test'
  const pasta = mkdtempSync(path.join(tmpdir(), 'balaio-api-'))
  const arquivo = path.join(pasta, 'db.json')
  const servidor = criarServidor(arquivo).listen(0, '127.0.0.1')
  await new Promise((resolve) => servidor.once('listening', resolve))
  t.after(async () => {
    await new Promise((resolve) => servidor.close(resolve))
    rmSync(pasta, { recursive: true, force: true })
  })
  const base = `http://127.0.0.1:${servidor.address().port}/api/v1`
  const request = async (url, body, method = 'POST', headers = {}) => {
    const opcoes = body === undefined && Object.keys(headers).length === 0
      ? undefined
      : { method: body === undefined ? method : method, headers: { 'Content-Type': 'application/json', ...headers }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) }
    const res = await fetch(base + url, opcoes)
    return { status: res.status, cookie: res.headers.get('set-cookie'), ...await res.json() }
  }
  for (const recurso of ['pecas', 'artesaos', 'coletivos', 'eventos', 'videos', 'pedidos', 'artesao/conversas', 'artesao/pedidos-pendentes', 'admin/curadoria', 'admin/mediacoes']) {
    const res = await request('/' + recurso)
    assert.equal(res.status, 200, recurso)
    assert.equal(res.erro, null, recurso)
    assert.ok(res.dados.length > 0, recurso)
  }
  assert.ok((await request('/referencias')).dados.tecnicas.length)
  assert.equal((await request('/usuario')).status, 401)
  assert.equal((await request('/auth/cadastro', { nome: '', email: 'invalido', senha: '123' })).status, 400)
  const cadastro = await request('/auth/cadastro', { nome: 'Ally Show', email: 'ALLYSHOW@gmail.com', senha: 'senhaforte', perfil: 'comprador' })
  assert.equal(cadastro.status, 201)
  assert.equal(cadastro.dados.email, 'allyshow@gmail.com')
  assert.ok(!('senhaHash' in cadastro.dados))
  const cookie = cadastro.cookie.split(';')[0]
  assert.equal((await request('/usuario', undefined, 'GET', { Cookie: cookie })).dados.nome, 'Ally Show')
  const endereco = await request('/usuario/enderecos', { apelido: 'Casa', rua: 'Rua do teste, 1', bairro: 'Centro', cep: '50000-000' }, 'POST', { Cookie: cookie })
  assert.equal(endereco.status, 201)
  assert.equal((await request(`/usuario/enderecos/${endereco.dados.id}`, { rua: 'Rua atualizada, 2' }, 'PATCH', { Cookie: cookie })).dados.rua, 'Rua atualizada, 2')
  assert.equal((await request('/usuario', { nome: 'Ally Atualizado', email: 'allyshow@gmail.com', telefone: '81999990000' }, 'PATCH', { Cookie: cookie })).dados.nome, 'Ally Atualizado')
  assert.equal((await request('/auth/cadastro', { nome: 'Outro', email: 'allyshow@gmail.com', senha: 'senhaforte' })).status, 409)
  assert.equal((await request('/auth/logout', {}, 'POST', { Cookie: cookie })).status, 200)
  assert.equal((await request('/usuario', undefined, 'GET', { Cookie: cookie })).status, 401)
  assert.equal((await request('/auth/login', { email: 'allyshow@gmail.com', senha: 'errada' })).status, 401)
  const login = await request('/auth/login', { email: 'allyshow@gmail.com', senha: 'senhaforte' })
  assert.equal(login.status, 200)
  assert.ok(login.cookie)
  assert.equal((await request('/auth/recuperacao', { email: 'allyshow@gmail.com' })).status, 201)
  const vendedor = await request('/auth/cadastro', { nome: 'Artesã Teste', email: 'artesa@teste.com', senha: 'senhaforte', perfil: 'artesao', territorio: 'Cariri', tecnica: 'Xilogravura' })
  assert.equal(vendedor.status, 201)
  assert.ok(vendedor.dados.artesaoId)
  const cookieVendedor = vendedor.cookie.split(';')[0]
  assert.equal((await request('/artesao/me', undefined, 'GET', { Cookie: cookieVendedor })).dados.nome, 'Artesã Teste')
  assert.equal((await request('/artesao/me', { atelie: 'Novo Ateliê' }, 'PATCH', { Cookie: cookieVendedor })).dados.atelie, 'Novo Ateliê')
  const estado = await request('/estado')
  const cookieCliente = estado.cookie.split(';')[0]
  assert.deepEqual((await request('/estado/favoritos', { favoritos: ['teste'] }, 'PUT', { Cookie: cookieCliente })).dados, ['teste'])
  assert.deepEqual((await request('/estado/videosCurtidos', { videosCurtidos: ['v-001'] }, 'PUT', { Cookie: cookieCliente })).dados, ['v-001'])
  assert.deepEqual((await request('/estado', undefined, 'GET', { Cookie: cookieCliente })).dados.videosCurtidos, ['v-001'])
  const todas = await request('/pecas')
  const pagina = await request('/pecas?pagina=2&tamanho=3&ordenar=preco-asc')
  assert.equal(pagina.dados.length, 3)
  assert.equal(pagina.paginacao.total, todas.dados.length)
  assert.equal(pagina.paginacao.pagina, 2)
  const preco = (p) => p.preco * (1 - (p.desconto || 0) / 100)
  assert.deepEqual(pagina.dados.map(preco), [...pagina.dados.map(preco)].sort((a, b) => a - b))
  assert.ok((await request('/pecas?q=ceramica')).dados.length)
  assert.equal((await request('/pecas?q=inexistente')).paginacao.total, 0)
  const primeira = todas.dados[0]
  const pergunta = await request(`/pecas/${primeira.slug}/perguntas`, { pergunta: 'Como foi feita?' }, 'POST', { Cookie: login.cookie.split(';')[0] })
  assert.equal(pergunta.status, 201)
  assert.equal((await request(`/pecas/${primeira.slug}/perguntas`)).dados[0].pergunta, 'Como foi feita?')
  const relacionadas = await request(`/pecas/${primeira.slug}/relacionadas?limite=1`)
  assert.equal(relacionadas.dados.length, 1)
  assert.notEqual(relacionadas.dados[0].slug, primeira.slug)
  assert.ok((await request(`/artesaos/${primeira.artesao}/pecas`)).dados.every((p) => p.artesao === primeira.artesao))
  assert.equal((await request('/pecas/inexistente')).status, 404)
  assert.equal((await request('/pedidos/inexistente/conversa')).status, 404)
  const evento = (await request('/eventos')).dados[0]
  const novo = await request('/eventos', { ...evento, id: undefined, slug: 'evento-teste', nome: 'Evento de teste' })
  assert.equal(novo.status, 201)
  assert.equal((await request('/eventos/evento-teste')).dados.nome, 'Evento de teste')
  assert.equal((await request('/eventos', { ...evento, slug: 'evento-teste' })).status, 409)
  assert.equal((await request('/eventos/evento-teste', { nome: 'Atualizado' }, 'PATCH')).dados.nome, 'Atualizado')
  const compra = { itens: [{ slug: primeira.slug, quantidade: 1 }, { slug: todas.dados[1].slug, quantidade: 2 }], freteId: 'padrao', meio: 'pix', endereco: { cep: '52021030', endereco: 'Rua de teste', cidade: 'Recife', estado: 'PE' } }
  const cookieComprador = login.cookie.split(';')[0]
  const pedido = await request('/checkout', compra, 'POST', { Cookie: cookieComprador })
  assert.equal(pedido.status, 201)
  assert.equal(pedido.dados.compradorId, login.dados.id)
  assert.equal((await request('/checkout', { ...compra, compradorId: 'ninguem' })).status, 401)
  assert.equal(pedido.dados.total, Math.round((preco(primeira) + 2 * preco(todas.dados[1]) + 38.9) * 100) / 100)
  assert.equal(pedido.dados.itens.length, 2)
  assert.ok(!(await request('/pecas')).dados.some((item) => item.slug === primeira.slug), 'peça única vendida saiu da vitrine')
  assert.ok((await request('/pedidos', undefined, 'GET', { Cookie: cookieComprador })).dados.some((item) => item.id === pedido.dados.id))
  assert.ok(!(await request('/pedidos', undefined, 'GET', { Cookie: cookieVendedor })).dados.some((item) => item.id === pedido.dados.id))
  const emProducao = await request(`/pedidos/${pedido.dados.id}/estado`, { estado: 'producao' }, 'PATCH')
  assert.equal(emProducao.dados.estado, 'producao')
  assert.equal(emProducao.dados.etapas.find((etapa) => etapa.estado === 'producao').atual, true)
  assert.equal((await request(`/pedidos/${pedido.dados.id}/cancelar`, {}, 'PATCH', { Cookie: cookieComprador })).status, 409)
  const outraUnica = todas.dados.find((item) => item.disponibilidade === 'unica' && item.slug !== primeira.slug)
  const paraCancelar = await request('/checkout', { ...compra, itens: [{ slug: outraUnica.slug, quantidade: 1 }] }, 'POST', { Cookie: cookieComprador })
  assert.equal(paraCancelar.status, 201)
  const cancelado = await request(`/pedidos/${paraCancelar.dados.id}/cancelar`, {}, 'PATCH', { Cookie: cookieComprador })
  assert.equal(cancelado.dados.estado, 'cancelado')
  assert.ok((await request('/pecas')).dados.some((item) => item.slug === outraUnica.slug), 'peça única cancelada voltou à vitrine')
  assert.equal((await request('/checkout', { ...compra, itens: [] }, 'POST', { Cookie: cookieComprador })).status, 400)
  const mensagem = await request(`/pedidos/${pedido.dados.id}/conversa`, { texto: 'Olá!', autor: 'comprador', hora: 'agora' })
  assert.equal(mensagem.status, 201)
  assert.equal((await request(`/pedidos/${pedido.dados.id}/conversa`)).dados.length, 1)
  assert.equal((await request('/pedidos/PE-2026-8720/conversa')).dados.length, 0)
  const disco = JSON.parse(readFileSync(arquivo, 'utf8'))
  for (const [nome, colecao] of Object.entries(disco)) {
    if (Array.isArray(colecao)) assert.ok(colecao.every((item) => item.id !== undefined), `${nome} contém item sem id`)
  }
  assert.ok(disco.usuarios.some((usuario) => usuario.email === 'allyshow@gmail.com' && usuario.senhaHash))
  assert.ok(!disco.usuarios.some((usuario) => 'senha' in usuario))
  assert.ok(disco.pedidos.some((p) => p.id === pedido.dados.id))
  assert.equal(disco.eventos.find((e) => e.slug === 'evento-teste').nome, 'Atualizado')
  assert.equal((await request('/eventos/evento-teste', {}, 'DELETE')).status, 200)
  assert.equal((await request('/eventos/evento-teste')).status, 404)
  const pecaNova = { ...primeira, id: undefined, slug: 'peca-teste', situacao: 'curadoria' }
  assert.equal((await request('/pecas', { ...pecaNova, tipo: 'Inexistente' })).status, 400)
  assert.equal((await request('/pecas', pecaNova)).status, 201)
  assert.ok(!(await request('/pecas')).dados.some((p) => p.slug === 'peca-teste'))
  const fila = (await request('/admin/curadoria')).dados.find((p) => p.pecaSlug === 'peca-teste')
  assert.ok(fila)
  assert.equal((await request(`/admin/curadoria/${fila.id}/decisao`, { decisao: 'aprovada' })).status, 200)
  assert.ok((await request('/pecas')).dados.some((p) => p.slug === 'peca-teste'))
  assert.equal((await request('/pecas/peca-teste', { preco: 321 }, 'PATCH')).dados.preco, 321)
  assert.equal((await request('/pecas/peca-teste', { disponibilidade: 'encomenda' }, 'PATCH')).status, 400)
  assert.equal((await request('/pecas/peca-teste', { disponibilidade: 'encomenda', prazoProducaoDias: 12 }, 'PATCH')).dados.prazoProducaoDias, 12)
  assert.equal((await request('/pecas/peca-teste', {}, 'DELETE')).status, 200)
  assert.equal((await request('/pecas/peca-teste')).status, 404)
  assert.equal((await request('/pedidos/PE-2026-8720/avaliacao', { nota: 0 })).status, 400)
  assert.equal((await request('/pedidos/PE-2026-8720/avaliacao', { nota: 5, comentario: 'Ótima peça', aspectos: [] })).status, 201)
  assert.equal((await request('/pedidos/PE-2026-8720')).dados.avaliado, true)
  assert.equal((await request('/pedidos/PE-2026-8720/avaliacao', { nota: 5 })).status, 409)
  const mediacao = { id: 'MED-teste', pedido: pedido.dados.id, assunto: 'Ajuda', relato: 'Preciso de ajuda', solucao: 'conversa' }
  assert.equal((await request('/admin/mediacoes', mediacao)).status, 201)
  assert.equal((await request('/admin/mediacoes', mediacao)).status, 409)
  assert.equal((await request('/eventos?lat=-8&lng=-35')).dados.length, (await request('/eventos')).dados.length)
  assert.equal((await request('/eventos?lat=200&lng=0')).status, 400)

  const demo = await request('/auth/entrar', { email: 'nuca@exemplo.com', senha: 'balaio123' })
  assert.equal(demo.status, 200)
  assert.equal(demo.dados.artesao, 'mestre-nuca')
  assert.equal(demo.dados.senha, undefined)
  const pecaDoNuca = todas.dados.find((item) => item.artesao === 'mestre-nuca' && item.disponibilidade !== 'unica')
  const paraRecusar = await request('/checkout', { ...compra, itens: [{ slug: pecaDoNuca.slug, quantidade: 1 }] }, 'POST', { Cookie: cookieComprador })
  const rejeitado = await request(`/pedidos/${paraRecusar.dados.id}/recusar`, { motivo: 'Não consigo atender dentro do prazo.' }, 'PATCH', { Cookie: demo.cookie.split(';')[0] })
  assert.equal(rejeitado.dados.estado, 'recusado')
  assert.equal(rejeitado.dados.motivoEncerramento, 'Não consigo atender dentro do prazo.')
  const recusado = await request('/auth/entrar', { email: 'nuca@exemplo.com', senha: 'errada123' })
  assert.equal(recusado.status, 401)
  assert.equal(recusado.erro.codigo, 'CREDENCIAIS_INVALIDAS')
  assert.equal((await request('/auth/cadastro', { nome: 'Ana', email: 'ana@x.com', senha: 'curta', papel: 'artesao' })).status, 400)
  const cadastroArtesao = await request('/auth/cadastro', { nome: 'Mestre Nuca', email: 'Nova@Exemplo.com', senha: 'segredo123', papel: 'artesao', territorio: 'Mata Norte', tecnica: 'Xilogravura' })
  assert.equal(cadastroArtesao.status, 201)
  assert.equal(cadastroArtesao.dados.artesao, 'mestre-nuca-2')
  assert.equal((await request('/artesaos/mestre-nuca-2')).dados.nome, 'Mestre Nuca')
  assert.equal((await request('/auth/cadastro', { nome: 'Outra', email: 'nova@exemplo.com', senha: 'segredo123', papel: 'comprador' })).erro.codigo, 'EMAIL_EM_USO')
  assert.equal((await request('/auth/entrar', { email: 'nova@exemplo.com', senha: 'segredo123' })).dados.papel, 'artesao')
  assert.equal((await request('/usuarios')).status, 404)
  const perfil = await request('/artesaos/mestre-dila', { atelie: '  Ateliê Novo  ', historia: 'Goiva desde menino.', territorio: 'Bezerros, Agreste', imagem: 'data:image/png;base64,iVBORw0KGgo=', selo: false }, 'PATCH')
  assert.equal(perfil.status, 200)
  assert.equal(perfil.dados.atelie, 'Ateliê Novo')
  assert.equal(perfil.dados.selo, true)
  assert.equal((await request('/artesaos/mestre-dila')).dados.territorio, 'Bezerros, Agreste')
  const fotoInvalida = await request('/artesaos/mestre-dila', { imagem: 'data:image/gif;base64,R0lGOD' }, 'PATCH')
  assert.equal(fotoInvalida.status, 400)
  assert.equal(fotoInvalida.erro.codigo, 'FOTO_INVALIDA')
  assert.equal((await request('/artesaos/mestre-dila', { nome: ' ' }, 'PATCH')).status, 400)
  assert.equal((await request('/artesaos/inexistente', { nome: 'X' }, 'PATCH')).status, 404)
  const padrao = await request('/artesaos/mestre-dila/configuracoes')
  assert.equal(padrao.dados.prazoPadraoDias, 15)
  const envio = await request('/artesaos/mestre-dila/configuracoes', { cepOrigem: '55640-000', prazoPadraoDias: 20 }, 'PATCH')
  assert.equal(envio.status, 200)
  assert.equal(envio.dados.aceitaEncomendas, true)
  const pix = await request('/artesaos/mestre-dila/configuracoes', { chavePix: 'dila@exemplo.com' }, 'PATCH')
  assert.equal(pix.dados.cepOrigem, '55640-000')
  assert.equal(pix.dados.chavePix, 'dila@exemplo.com')
  assert.equal((await request('/artesaos/mestre-dila/configuracoes', { cepOrigem: '123' }, 'PATCH')).status, 400)
  assert.equal((await request('/artesaos/mestre-dila/configuracoes', { prazoPadraoDias: 500 }, 'PATCH')).status, 400)
  assert.equal((await request('/artesaos/mestre-dila/configuracoes', {}, 'PATCH')).status, 400)
  assert.equal((await request('/configuracoesAtelie')).status, 404)
  assert.equal((await request('/artesaos/mestre-dila')).dados.chavePix, undefined)
  assert.ok((await request('/artesao/pedidos-pendentes?artesao=dona-bia-do-ipojuca')).dados.length > 0)
  assert.equal((await request('/artesao/pedidos-pendentes?artesao=mestre-dila')).dados.length, 0)
  assert.ok((await request('/artesao/conversas?artesao=mestre-nuca')).dados.some((c) => c.id === 'PE-2026-8941'))
  assert.equal((await request('/auth/entrar', { email: 'admin@exemplo.com', senha: 'balaio123' })).dados.papel, 'admin')
  assert.equal((await request('/auth/cadastro', { nome: 'Intruso', email: 'x@exemplo.com', senha: 'segredo123', papel: 'admin' })).status, 400)
  assert.ok((await request('/pedidos?compradorId=u-carlos')).dados.every((p) => p.compradorId === 'u-carlos'))
  assert.equal((await request('/pedidos?compradorId=u-nuca')).dados.length, 0)
  const conta = cadastroArtesao.dados.id
  const autorizacaoConta = { Cookie: cadastroArtesao.cookie.split(';')[0] }
  assert.equal((await request(`/conta/${conta}`, { nome: 'Nuca Filho', email: 'carlos@exemplo.com' }, 'PATCH', autorizacaoConta)).status, 409)
  assert.equal((await request(`/conta/${conta}`, { nome: 'Nuca Filho', email: 'nova@exemplo.com', telefone: '81' }, 'PATCH', autorizacaoConta)).dados.nome, 'Nuca Filho')
  assert.equal((await request(`/conta/${conta}/senha`, { senhaAtual: 'errada', novaSenha: 'outra12345' }, 'POST', autorizacaoConta)).status, 401)
  assert.equal((await request(`/conta/${conta}/senha`, { senhaAtual: 'segredo123', novaSenha: 'outra12345' }, 'POST', autorizacaoConta)).status, 200)
  assert.equal((await request('/auth/entrar', { email: 'nova@exemplo.com', senha: 'outra12345' })).status, 200)
})

test('completa tipo das peças e referências em um banco antigo', async () => {
  process.env.NODE_ENV = 'test'
  const pasta = mkdtempSync(path.join(tmpdir(), 'balaio-api-'))
  const arquivo = path.join(pasta, 'db.json')
  const antigo = JSON.parse(readFileSync(path.join(__dirname, 'seed.json'), 'utf8'))
  for (const peca of antigo.pecas) delete peca.tipo
  delete antigo.referencias.tipos
  writeFileSync(arquivo, JSON.stringify(antigo))
  criarServidor(arquivo)
  const atualizado = JSON.parse(readFileSync(arquivo, 'utf8'))
  rmSync(pasta, { recursive: true, force: true })
  assert.ok(atualizado.pecas.every((p) => p.tipo))
  assert.equal(atualizado.referencias.tipos.length, 6)
})
